import React from 'react';
import {Pressable, PressableProps} from 'react-native';

import {DynamicViewProps} from './DynamicView';

const RView = ({
  children,
  flex,
  flexDirection,
  justifyContent,
  alignItems,
  padding,
  paddingRight,
  paddingLeft,
  paddingTop,
  paddingBottom,
  paddingVertical,
  paddingHorizontal,
  margin,
  marginRight,
  marginLeft,
  marginTop,
  marginBottom,
  marginVertical,
  marginHorizontal,
  style,
  borderTopWidth,
  borderTopColor,
  borderLeftWidth,
  borderLeftColor,
  borderRightWidth,
  borderRightColor,
  borderBottomWidth,
  borderBottomColor,
  borderWidth,
  borderColor,
  borderRadius,
  borderTopLeftRadius,
  borderTopRightRadius,
  borderBottomLeftRadius,
  borderBottomRightRadius,
  width,
  backgroundColor,
  height,
  position,
  left,
  right,
  top,
  bottom,
  display,
  testID,
  opacity,
  zIndex,
  onPress,
  disabled,
}: DynamicViewProps & PressableProps) => (
  <Pressable
    testID={testID}
    disabled={disabled}
    onPress={onPress}
    style={[
      !!flex && {flex},
      !!flexDirection && {flexDirection},
      !!justifyContent && {justifyContent},
      !!alignItems && {alignItems},
      !!padding && {padding},
      !!paddingTop && {paddingTop},
      !!paddingRight && {paddingRight},
      !!paddingBottom && {paddingBottom},
      !!paddingLeft && {paddingLeft},
      !!paddingVertical && {paddingVertical},
      !!paddingHorizontal && {paddingHorizontal},
      !!margin && {margin},
      !!marginTop && {marginTop},
      !!marginRight && {marginRight},
      !!marginBottom && {marginBottom},
      !!marginLeft && {marginLeft},
      !!marginVertical && {marginVertical},
      !!marginHorizontal && {marginHorizontal},
      style && style,
      !!borderTopWidth && {borderTopWidth},
      !!borderTopColor && {borderTopColor},
      !!borderLeftWidth && {borderLeftWidth},
      !!borderLeftColor && {borderLeftColor},
      !!borderRightWidth && {borderRightWidth},
      !!borderRightColor && {borderRightColor},
      !!borderBottomWidth && {borderBottomWidth},
      !!borderBottomColor && {borderBottomColor},
      !!borderWidth && {borderWidth},
      !!borderColor && {borderColor},
      !!borderRadius && {borderRadius},
      !!borderTopLeftRadius && {borderTopLeftRadius},
      !!borderTopRightRadius && {borderTopRightRadius},
      !!borderBottomLeftRadius && {borderBottomLeftRadius},
      !!borderBottomRightRadius && {borderBottomRightRadius},
      !!width && {width},
      !!backgroundColor && {backgroundColor},
      !!height && {height},
      !!position && {position},
      !!left && {left},
      !!right && {right},
      !!top && {top},
      !!bottom && {bottom},
      !!display && {display},
      !!opacity && {opacity},
      !!zIndex && {zIndex},
    ]}>
    {children}
  </Pressable>
);

export default RView;
